python3 inference.py --path '../../Input/Ujjwal/Data/' --mode 'simpl_v1_1' 
python3 inference.py --path '../../Input/Ujjwal/Data/' --mode 'simpl_v1_4' 
python3 inference.py --path '../../Input/Ujjwal/Data/' --mode 'pslbl_v1_0' 
python3 inference.py --path '../../Input/Ujjwal/Data/' --mode 'simpl_v2_8' 
python3 inference.py --path '../../Input/Ujjwal/Data/' --mode 'simpl_v2_5' 
python3 inference.py --path '../../Input/Ujjwal/Data/' --mode 'pslbl_v2_7' 
python3 inference.py --path '../../Input/Ujjwal/Data/' --mode 'simpl_v3_6' 
python3 inference.py --path '../../Input/Ujjwal/Data/' --mode 'simpl_v3_3' 
python3 inference.py --path '../../Input/Ujjwal/Data/' --mode 'pslbl_v3_8'
python3 post_process.py --path '../../Input/Ujjwal/Data/'